### ISSUE TITLE
Constant crashing

### ISSUE THREAD

**Issue by Catopbleas** [Northfear/fallout2-ce-vita#20] opened 2022-12-29 05:16 UTC
First of all, I think this port is amazing and it runs beautifully. There’s just one reoccurring issue that completely plagues my experience which is the constant crashing. It’s like every time I go to a different area or there’s a transition change there’s a dice roll on wether it’s going to crash or not. It starts to feel like Groundhog Day, the game. It’s weird because there doesn’t seem to be a lead up to the crash, not even a decrease in performance . It just does all of a sudden. Any possible fixes for this atm or is it still being worked on?

**Comment by Northfear** [comment] 2023-01-04 08:03
Hi. I think this might've been fixed in upstream (some crashes that were related to ARM). Unfortunately I had almost no time to spare for the project recently, but I'll try to update it to the latest version in the nearest future and will check the stability situation again

**Comment by Catopbleas** [comment] 2023-01-04 14:31
Thank you for the reply. The game runs almost perfectly except for the crashes towards the end game. I should have you know that I didn’t always delete the save slots, I did overwrite quite a few times but I hardly believe the issue stems from that.

**Comment by Northfear** [comment] 2023-01-08 20:43
I've made a latest build. Haven't got any time to test it unfortunately. Let me know how it works and send the psp2dmp files of the crashes (in ux0:data/) if the crashes are still occurring.
[fallout2-ce.zip](https://github.com/Northfear/fallout2-ce-vita/files/10369446/fallout2-ce.zip)

**Comment by Catopbleas** [comment] 2023-01-09 03:08
Here you go [psp2dmp.zip](https://github.com/Northfear/fallout2-ce-vita/files/10370115/psp2dmp.zip)

Yup the crashes are still there. I did notice a screen fade in/fade out ingame when exiting grid, mind you this didn't negatively impact gameplay, just letting you know in case it wasn't intended. 

Hey man dont sweat it, Im surprised I was able to play for this long. I am at end game lvl 24

**Comment by Northfear** [comment] 2023-01-10 18:36
Is there a savegame for reproduction? How exactly was it triggered?
Looks like this crash is related to some bug in fallout2-ce interpreter itself and not Vita port.

**Comment by Catopbleas** [comment] 2023-01-11 19:02
Here: 
[SLOT10.zip](https://github.com/Northfear/fallout2-ce-vita/files/10395221/SLOT10.zip)
Im sorry, im not very knowledgeable in regards to this, does that mean the problem is exclusive to my vita?

**Comment by Catopbleas** [comment] 2023-01-11 21:16
Pretty much everytime I travel to a different location or exit grid from say ncr downtown to bazaar its a gamble on the game crashing or not. The crashes became more and more consistent as I played. Instead of a 50% crash rate I get a 90% crash rate, so much so that I have to save pretty much everytime before doing any of such actions.

**Comment by Northfear** [comment] 2023-01-20 21:04
Yeah, was able to reproduce it on Linux build of fallout2-ce too. Reported it to the original fallout2-ce author. We'll see if it's something wrong with the game or is it the savegame that became corrupted somehow.

**Comment by Northfear** [comment] 2023-01-21 15:26
This one was fixed upstream
Give development build a try
https://github.com/Northfear/fallout2-ce-vita/releases/tag/latest

**Comment by Catopbleas** [comment] 2023-01-21 16:53
Thank you Im gonna give it a try

**Closed** 2023-01-22 16:58 UTC
