### ISSUE TITLE
CTD C2-12828-1 when exiting Vault 13 cave

### ISSUE THREAD

**Issue by zachary-cauchi** [Northfear/fallout2-ce-vita#19] opened 2022-12-08 20:26 UTC
Hi there. So far, completed the first visit to Vault 13 and was about to leave. When I try to leave - either through the Highwayman or on foot - The game instantly crashes with the usual C2-12828-1 error. When I reloaded and tried leaving only after arriving at Vault 13, I was able to load the map without issues. Not sure if this is related, but Gruthar wasn't in the vault either. Any help would be greatly appreciated, thanks.

**Comment by Northfear** [comment] 2022-12-19 08:45
I think the missing Gruthar bug is from vanilla. Anyway. Are they reproducible on PC too? There were some updates after the last release, so I might as well update the port too when I'll get some time.

**Comment by zachary-cauchi** [comment] 2022-12-21 07:51
Tried loading the file on fallout2-ce on pc, but it wouldn't load, saying there was an error. I tried copying the installation files again (`master.dat`, `critter.dat`, etc) and saw that I was missing the `patch000.dat` file. When I added that and tried reloading the save, it showed the same error and wouldn't load. I guess there was something missing because of the patch file. I started a new save file in the meantime.

**Comment by Northfear** [comment] 2023-01-10 18:38
Sorry for the late response. Could you drop a savegame and instruction of how to reproduce this bug please? I might finally look into it

**Comment by zachary-cauchi** [comment] 2023-01-11 08:22
Hi @Northfear. Shall do later today.

**Comment by zachary-cauchi** [comment] 2023-01-12 19:51
Hi @Northfear. Sorry for the late reply.

I've attached the saves in [SAVEGAMES.zip](https://github.com/Northfear/fallout2-ce-vita/files/10405435/SAVEGAMES.zip). The steps to reproduce should be like this:
* Ensure Fallout2-ce-vita is installed on the PSVita and running (at the time I **did not have the patch000.dat file installed**).
* Extract the contents of the zip file to the save slots location on the vita (`ux0:data/fallout2/data/SAVEGAME`).
* Open up the game and load the slot with the most recent date (it should show the player in the vault 13 cave entrance next to the highwayman).
* Load it.
* You should appear in the cave next to the highwayman.
* Try to exit the cave.
* The error should occur.

**Comment by Northfear** [comment] 2023-01-20 21:39
Huh. I can't load any of your games. Probably due to different game data.
Issue seems really similar to https://github.com/Northfear/fallout2-ce-vita/issues/20
And I've forwarded it already to the original project. It's not crashing 100% of the time, right?

**Comment by Northfear** [comment] 2023-01-21 15:27
I think this might've been fixed now
Here's a dev build
https://github.com/Northfear/fallout2-ce-vita/releases/tag/latest

**Comment by zachary-cauchi** [comment] 2023-01-22 00:43
Hi Northfear. Yeah, that's most likely the reason. I think this can be marked closed since I can't even reproduce it after reinstalling the game and app.

**Closed** 2023-01-22 16:55 UTC
